import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Spotlight } from "@/components/ui/Spotlight";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className} >
      <Spotlight/>
        <div className="relative w-full flex items-center justify-center ">
          <Navbar/>
        </div>

        {children}             {/* children comming from current route(folder) i.e if current route is '/chai' then its content(layout,page) get painted here*/}
      </body>
    </html>
  );
}
