import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="border border-2 border-green-500">
      <body className={inter.className} >
      <h2 className="border border-2 border-red-500">Nav Item</h2>
        {children}             {/* children comming from current route(folder) i.e if current route is '/chai' then its content(layout,page) get painted here*/}
      </body>
    </html>
  );
}
